gui:
  theme:
    selectedLineBgColor:
      - "#3B4252"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
os:
  openLink: 'xdg-open {{link}} | null'
  open: 'xdg-open {{filename}} | null'
